### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by morgoth** [jboltz88/braze_ruby#3]
Would it be possible to setup Travis CI for automatic tests on this repo?

**Comment by jboltz88** [comment]
@morgoth I've added you as a collaborator for the project since I no longer have need of the gem, myself. Feel free to make contributions as you see fit, unless you'd rather just fork the project.

**Comment by morgoth** [comment]
Thanks, I'll see what I can do. Would be much better to not have yet another fork, but most recent state in one place so that maybe community could benefit

**Comment by morgoth** [comment]
@jboltz88 it is not possible to setup travis on forked repository, but instead could you maybe apply for Github Actions on https://github.com/features/actions - I believe this way we could setup CI for testing.

**Comment by jboltz88** [comment]
I've signed up my account, waiting on however long the queue is for approval.

**Comment by morgoth** [comment]
Yes, that might take a while. Thanks

**Comment by morgoth** [comment]
I added it in https://github.com/jboltz88/braze_ruby/pull/6/files - thanks
