### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by morgoth** [jboltz88/braze_ruby#4]
@jboltz88 could you please release a new version of gem with recent changes or if you don't mind you could add me to gem owners so I can do it myself.
My rubygems mail is: "w.wnetrzak@gmail.com"

**Comment by jboltz88** [comment]
Hey, sorry, totally spaced on releasing those changes. I went ahead and
added you as an owner on rubygems.

**Comment by morgoth** [comment]
Thank you. Done
